/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CheckboxChecked, } from "./interface";
export namespace Components {
    interface CheckBox {
        /**
          * Tracks wether this component has been checked or not. Unchecked by default. Can be instantiated with a different value because prop is mutable.
         */
        "checked": boolean;
    }
}
declare global {
    interface HTMLCheckBoxElement extends Components.CheckBox, HTMLStencilElement {
    }
    var HTMLCheckBoxElement: {
        prototype: HTMLCheckBoxElement;
        new (): HTMLCheckBoxElement;
    };
    interface HTMLElementTagNameMap {
        "check-box": HTMLCheckBoxElement;
    }
}
declare namespace LocalJSX {
    interface CheckBox {
        /**
          * Tracks wether this component has been checked or not. Unchecked by default. Can be instantiated with a different value because prop is mutable.
         */
        "checked"?: boolean;
        /**
          * This event should be emitted when the checkbox ingests input from user
         */
        "onChanged"?: (event: CustomEvent<CheckboxChecked>) => void;
        /**
          * Internal event not exposed
         */
        "onCheckboxChecked"?: (event: CustomEvent<void>) => void;
        /**
          * Internal Event not exposed
         */
        "onCheckboxUnchecked"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "check-box": CheckBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "check-box": LocalJSX.CheckBox & JSXBase.HTMLAttributes<HTMLCheckBoxElement>;
        }
    }
}
